version: '3.9'

services:
  db:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: auth_app
    depends_on:
      - db
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - .:/cmd
    restart: always

  migrate:
    image: migrate/migrate
    container_name: migrate_auth
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate", 
                  "-path", "/migrations", 
                  "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable", 
                  "up" ]

volumes:
  pgdata:
