version: '3.9'

services:
  db:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: auth_app
    depends_on:
      - db
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - .:/cmd
    restart: always

  migrate:
    image: alpine:3.18
    container_name: migrate_auth
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint:
      - sh
      - -c
      - |
        apk add --no-cache curl bash && \
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz && \
        mv migrate /usr/bin/ && \
        chmod +x /wait-for-it.sh && \
        /wait-for-it.sh db:5432 -- migrate -path=/migrations -database=postgres://postgres:postgres@db:5432/postgres?sslmode=disable up

volumes:
  pgdata:
